/**
 * Editorial product seed for Adanola.
 * Images use high-quality Unsplash activewear photography.
 * When Cloudinary is configured, seed.js can re-host them under your cloud.
 */

const IMG = {
  hero: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1920&q=80',
  hero2: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1920&q=80',
  editorial1: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=1200&q=80',
  editorial2: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1200&q=80',
  editorial3: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=1200&q=80',
  editorial4: 'https://images.unsplash.com/photo-1550345332-09e3ac987658?w=1200&q=80',
  p1: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80',
  p2: 'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=800&q=80',
  p3: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80',
  p4: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80',
  p5: 'https://images.unsplash.com/photo-1506629082955-511b1aa78283?w=800&q=80',
  p6: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&q=80',
  p7: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&q=80',
  p8: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80',
  p9: 'https://images.unsplash.com/photo-1523381215767-4bb7c1c5b4b3?w=800&q=80',
  p10: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
  p11: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=800&q=80',
  p12: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800&q=80',
};

export const SITE = {
  announcement: 'FREE Standard Delivery on orders over €125',
  hero: {
    headline: 'The Ultimate staples',
    cta: 'SHOP ACTIVE',
    ctaLink: '/shop?category=active',
    images: [IMG.hero, IMG.hero2],
  },
  editorial: [
    { image: IMG.editorial1, alt: 'Movement in motion' },
    { image: IMG.editorial2, alt: 'Studio stretch' },
    { image: IMG.editorial3, alt: 'City stride' },
    { image: IMG.editorial4, alt: 'Morning light' },
  ],
  categories: [
    { slug: 'shop', label: 'SHOP' },
    { slug: 'active', label: 'ACTIVE' },
    { slug: 'sweats', label: 'SWEATS' },
    { slug: 'spring-summer', label: 'SPRING SUMMER' },
  ],
  filters: ['HOODIES', 'SHORTS', 'T-SHIRTS', 'LEGGINGS', 'SETS'],
};

export const products = [
  {
    name: 'Essential Oversized Hoodie',
    slug: 'essential-oversized-hoodie',
    description: 'A whisper-weight fleece hoodie cut for movement. Soft hand-feel, dropped shoulder, ribbed cuffs. The ultimate off-duty staple.',
    price: 68,
    category: 'hoodies',
    tags: ['sweats', 'active', 'new'],
    colors: [
      { name: 'Carbon', hex: '#1d1d1d' },
      { name: 'Stone', hex: '#cccccc' },
      { name: 'Driftwood', hex: '#dfccbe' },
      { name: 'Olive', hex: '#636355' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: [IMG.p1, IMG.p2],
    featured: true,
    trending: true,
    newArrival: true,
  },
  {
    name: 'Performance Legging',
    slug: 'performance-legging',
    description: 'High-rise compression with a second-skin finish. Sculpting seams, flatlock construction, matte surface that photographs clean.',
    price: 58,
    category: 'leggings',
    tags: ['active', 'shop'],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Slate', hex: '#2f3440' },
      { name: 'Maroon', hex: '#523037' },
      { name: 'Deep Iris', hex: '#222845' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    images: [IMG.p5, IMG.editorial1],
    featured: true,
    trending: true,
  },
  {
    name: 'Relaxed Crew Sweat',
    slug: 'relaxed-crew-sweat',
    description: 'Boxy crew in heavyweight cotton loopback. Clean neckline, minimal branding — made for editorial layering.',
    price: 62,
    category: 'sweats',
    tags: ['sweats', 'shop'],
    colors: [
      { name: 'Paper', hex: '#ffffff' },
      { name: 'Warm Fog', hex: '#f0efe7' },
      { name: 'Pewter', hex: '#677284' },
      { name: 'Carbon', hex: '#000000' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [IMG.p3, IMG.p4],
    featured: true,
    newArrival: true,
  },
  {
    name: 'Cropped Active Tee',
    slug: 'cropped-active-tee',
    description: 'Lightweight jersey crop with a clean hem. Breathable, slightly sheer in motion light — a quiet essential.',
    price: 38,
    category: 't-shirts',
    tags: ['active', 'spring-summer', 'shop'],
    colors: [
      { name: 'White', hex: '#ffffff' },
      { name: 'Black', hex: '#000000' },
      { name: 'Pale Tide', hex: '#badce4' },
      { name: 'Blush Sand', hex: '#f5ebd5' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    images: [IMG.p6, IMG.p7],
    trending: true,
  },
  {
    name: 'Studio Short',
    slug: 'studio-short',
    description: 'Mid-thigh short with an elastic waist and hidden pocket. Soft stretch woven that holds its line on the move.',
    price: 48,
    category: 'shorts',
    tags: ['active', 'spring-summer'],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Olive', hex: '#636355' },
      { name: 'Stone', hex: '#cccccc' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    images: [IMG.p8, IMG.editorial2],
    featured: true,
  },
  {
    name: 'Zip Track Jacket',
    slug: 'zip-track-jacket',
    description: 'Slim track jacket with tonal zip and rib finishes. Designed to sit over sets without bulk.',
    price: 88,
    category: 'active',
    tags: ['active', 'shop', 'new'],
    colors: [
      { name: 'Onyx', hex: '#1d1d1d' },
      { name: 'Slate', hex: '#2f3440' },
      { name: 'Driftwood', hex: '#dfccbe' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [IMG.p9, IMG.p10],
    newArrival: true,
    trending: true,
  },
  {
    name: 'Ribbed Tank Set',
    slug: 'ribbed-tank-set',
    description: 'Matching tank and short set in fine rib. Soft stretch, clean lines — a full look in one piece.',
    price: 78,
    category: 'sets',
    tags: ['active', 'spring-summer', 'shop'],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Maroon Clay', hex: '#523037' },
      { name: 'Pale Tide', hex: '#badce4' },
      { name: 'Warm Fog', hex: '#f0efe7' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    images: [IMG.p11, IMG.editorial3],
    featured: true,
    trending: true,
  },
  {
    name: 'Everyday Fleece Pant',
    slug: 'everyday-fleece-pant',
    description: 'Tapered fleece pant with a soft drawcord. Straight through the thigh, clean hem — lounge to street.',
    price: 72,
    category: 'sweats',
    tags: ['sweats', 'shop'],
    colors: [
      { name: 'Carbon', hex: '#000000' },
      { name: 'Stone', hex: '#cccccc' },
      { name: 'Olive', hex: '#636355' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: [IMG.p12, IMG.p1],
    featured: true,
  },
  {
    name: 'Soft Scoop Bra',
    slug: 'soft-scoop-bra',
    description: 'Low-support scoop with bonded edges. Invisible under tees, intentional on its own.',
    price: 42,
    category: 'active',
    tags: ['active', 'shop'],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'White', hex: '#ffffff' },
      { name: 'Deep Iris', hex: '#222845' },
      { name: 'Driftwood', hex: '#dfccbe' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    images: [IMG.editorial4, IMG.p5],
    newArrival: true,
  },
  {
    name: 'Boxy Pocket Tee',
    slug: 'boxy-pocket-tee',
    description: 'Heavy cotton tee with a single chest pocket. Square cut, dropped armhole, no logo noise.',
    price: 44,
    category: 't-shirts',
    tags: ['shop', 'spring-summer'],
    colors: [
      { name: 'White', hex: '#ffffff' },
      { name: 'Black', hex: '#000000' },
      { name: 'Blush Sand', hex: '#f5ebd5' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [IMG.p4, IMG.p6],
    trending: true,
  },
  {
    name: 'Split Hem Short',
    slug: 'split-hem-short',
    description: 'Running short with side splits and built-in liner. Lightweight, fast-drying, minimal branding.',
    price: 52,
    category: 'shorts',
    tags: ['active', 'spring-summer'],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Pewter', hex: '#677284' },
      { name: 'Pale Tide', hex: '#badce4' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    images: [IMG.p7, IMG.p8],
    featured: true,
  },
  {
    name: 'Half-Zip Fleece',
    slug: 'half-zip-fleece',
    description: 'Stand-collar half-zip in brushed fleece. Quiet hardware, clean placket — layering without volume.',
    price: 82,
    category: 'sweats',
    tags: ['sweats', 'active', 'new'],
    colors: [
      { name: 'Onyx', hex: '#1d1d1d' },
      { name: 'Warm Fog', hex: '#f0efe7' },
      { name: 'Olive', hex: '#636355' },
      { name: 'Slate', hex: '#2f3440' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [IMG.p2, IMG.p9],
    newArrival: true,
    trending: true,
  },
];

/** In-memory store used when MongoDB is not connected */
export function createMemoryStore() {
  const list = products.map((p, i) => ({
    ...p,
    _id: `mem_${i + 1}`,
    id: `mem_${i + 1}`,
    currency: 'EUR',
    inStock: true,
    stock: 50,
    cloudinaryIds: [],
    createdAt: new Date().toISOString(),
  }));

  return {
    products: list,
    users: [],
    orders: [],
  };
}

export { IMG };
